services:
    v2ray:
        ports:
            - 9001:9000
            - 19001:9000
            - 29001:9000
            - 39001:9000
        container_name: v2ray_latest
        restart: always
        volumes:
            - .:/etc/v2ray
        image: teddysun/v2ray
